name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # Tells GitHub where to find the lockfile for caching
          cache-dependency-path: './CalculatorReactApp/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: ./CalculatorReactApp

      - name: Build
        run: npm run build
        working-directory: ./CalculatorReactApp

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Points to the 'dist' folder inside your React app folder
          path: './CalculatorReactApp/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4